import React from 'react'
import AnimatedText from '@/components/AnimatedText'
import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import article1 from '../../public/images/articles/pagination component in reactjs.jpg';
import article2 from '../../public/images/articles/form validation in reactjs using custom react hook.png';
import { motion } from 'framer-motion'

const FramerImage = motion(Image)

const FeaturedArticle = ({ title, summary, link, img, time }) => {
    return (
        <li className='col-span-1 w-full p-4 bg-light border border-solid border-dark rounded-2xl relative'>
        <div className='absolute top-0 -right-3 -z-10 w-[101%] h-[103%] rounded-[2rem] bg-dark rounded-br-3xl' />
            <Link href={link} target='_blank' className='inline-block w-full cursor-pointer overflow-hidden rounded-lg'>
                <FramerImage
                    whileHover={{ scale: 1.05 }}
                    transition={{ duration: 0.2 }}
                    src={img}
                    alt={title}
                    className='w-full h-auto'
                />
            </Link>
            <Link href={link} target='_blank' className='w-full cursor-pointer overflow-hidden rounded-lg'>
                <h2 className='capitalize text-2xl font-bold my-2 hover:underline'>{title}</h2>
            </Link>
            <p className='text-sm mb-2'>{summary}</p>
            <span className='text-primary font-semibold'>{time}</span>
        </li>
    )
}

const articles = () => {
    return (
        <>
            <Head>
                <title>Sajid | Articles Page</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main className='w-full flex items-center justify-center overflow-hidden mb-16'>
                <Layout className='pt-16'>
                    <AnimatedText text={"Words Can Change The World! "} className='mb-16' />
                    <ul className='grid grid-cols-2 gap-16'>
                        <FeaturedArticle
                            title={"Build A Custom Pagination Component In Reactjs From Scratch"}
                            img={article1}
                            link={"/"}
                            summary={`Learn how to build a custom pagination component in ReactJS from scratch. 
                        Follow this step-by-step guide to integrate Pagination component in your ReactJS project.`}
                            time={"9 min read"}
                        />
                        <FeaturedArticle
                            title={"Build A Custom Pagination Component In Reactjs From Scratch"}
                            img={article2}
                            link={"/"}
                            summary={`Learn how to build a custom pagination component in ReactJS from scratch. 
                        Follow this step-by-step guide to integrate Pagination component in your ReactJS project.`}
                            time={"9 min read"}
                        />
                    </ul>
                </Layout>
            </main>
        </>
    )
}

export default articles